# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vigetlabs-routing-filter}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven Fuchs", "Brian Landau", "David Eisinger"]
  s.date = %q{2011-04-04}
  s.description = %q{Routing filters wraps around the complex beast that the Rails routing system is, allowing for unseen flexibility and power in Rails URL recognition and generation.}
  s.email = %q{svenfuchs@artweb-design.de}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "ci/Gemfile.rails-2.3.x",
    "ci/Gemfile.rails-2.3.x.lock",
    "ci/Gemfile.rails-3.x",
    "ci/Gemfile.rails-3.x.lock",
    "lib/routing-filter.rb",
    "lib/routing_filter.rb",
    "lib/routing_filter/adapters/rails_2.rb",
    "lib/routing_filter/adapters/rails_3.rb",
    "lib/routing_filter/chain.rb",
    "lib/routing_filter/filter.rb",
    "lib/routing_filter/filters/extension.rb",
    "lib/routing_filter/filters/locale.rb",
    "lib/routing_filter/filters/pagination.rb",
    "lib/routing_filter/filters/uuid.rb",
    "lib/routing_filter/version.rb",
    "test/all.rb",
    "test/filters/all_filters/generation.rb",
    "test/filters/all_filters/recognition.rb",
    "test/filters/all_filters_test.rb",
    "test/filters/extension_test.rb",
    "test/filters/locale_test.rb",
    "test/filters/pagination_test.rb",
    "test/filters/uuid_test.rb",
    "test/rails_test.rb",
    "test/routes_test.rb",
    "test/routing_filter_test.rb",
    "test/test_adapters/rails_2.rb",
    "test/test_adapters/rails_3.rb",
    "test/test_helper.rb",
    "vigetlabs-routing-filter.gemspec"
  ]
  s.homepage = %q{https://github.com/vigetlabs/routing-filter}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Routing filters wraps around the complex beast that the Rails routing system is, allowing for unseen flexibility and power in Rails URL recognition and generation.}
  s.test_files = [
    "test/all.rb",
    "test/filters/all_filters/generation.rb",
    "test/filters/all_filters/recognition.rb",
    "test/filters/all_filters_test.rb",
    "test/filters/extension_test.rb",
    "test/filters/locale_test.rb",
    "test/filters/pagination_test.rb",
    "test/filters/uuid_test.rb",
    "test/rails_test.rb",
    "test/routes_test.rb",
    "test/routing_filter_test.rb",
    "test/test_adapters/rails_2.rb",
    "test/test_adapters/rails_3.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 0"])
    else
      s.add_dependency(%q<actionpack>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 0"])
  end
end

